name: vArchaeology
version: '1.0-BETA'
main: asia.virtualmc.vArchaeology.Main
api-version: '1.21'
softdepend: [PlaceholderAPI]

commands:
  varch:
    description: A description of your command.
    usage: /<command>