name: vArchaeology
version: '1.0-BETA'
main: asia.virtualmc.vArchaeology.Main
api-version: '1.21'
softdepend: [PlaceholderAPI, CommandAPI, NBTAPI]

permissions:
  varchaeology.command.get:
    description: Allows viewing player archaeology data
    default: op
  varchaeology.command.exp:
    description: Allows modifying player archaeology experience
    default: op
  varchaeology.command.level:
    description: Allows modifying player archaeology level
    default: op
  varchaeology.command.reset:
    description: Allows resetting player archaeology data
    default: op
  varchaeology.exp.doublexp:
    description: Provides double XP bonus
    default: op